trigger: none

pr:
    branches:
         include:
         - master
    paths:
          exclude:
          - README.md
          - Scripts/*

pool:
 vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'
- script: MSBuild.exe DickinsonBros.SQL.sln -p:Configuration=$(buildConfiguration)
  displayName: 'MSBuild.exe DickinsonBros.SQL.sln -p:Configuration=$(buildConfiguration)'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
