trigger: none

pr:
    branches:
         include:
         - master
    paths:
          exclude:
          - README.md
          - Scripts/*

pool:
 vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.101'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '99529d92-bbfb-4792-8e59-537eb03ee040'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln' 
    configuration: $(buildConfiguration)
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
